In [41]:
# 시청 기록 파일 가져오기
import pandas as pd
import json

df=pd.read_json("시청 기록.json")

In [42]:
# 데이터 수정 => 최적화.
df.drop(columns= ["header","titleUrl","products","activityControls"], inplace = True)

In [43]:
# column 내 필요 없는 문자 대
df["title"]=df["title"].str.replace("을(를) 시청했습니다.","")
df

,title,subtitles,time
0,[𝙋𝙡𝙖𝙮𝙡𝙞𝙨𝙩] 상실의 시대…내가 사랑한 나의 미도리 | 감성 피아노,"[{'name': '노르웨이 숲 Norwegian Wood', 'url': 'htt...",2026-02-04T04:14:52.157Z
1,"과거에는 컴퓨터를 쓰기 위해 복잡한 코딩을 배워야 했지만, 이제는 컴퓨터랑 대화만 ...","[{'name': 'BZCF | 비즈까페', 'url': 'https://www.y...",2026-02-04T04:13:55.202Z
2,요즘 생각 : 너무 빠르고 무섭고 걱정도되고 슬프기도 하고 할수있는 것은 없고 그렇...,"[{'name': 'BZCF | 비즈까페', 'url': 'https://www.y...",2026-02-04T04:13:55.202Z
3,Blue Bird (2022 ver.) - Naruto Shippuuden OP3 ...,"[{'name': 'Animenz Piano Sheets', 'url': 'http...",2026-02-03T23:31:08.546Z
4,TWO-lives,"[{'name': 'Hiroyuki SAWANO - Topic', 'url': 'h...",2026-02-03T23:21:00.923Z
...,...,...,...
13043,승준이 우유 대소동,"[{'name': '동수칸TV', 'url': 'https://www.youtube...",2025-11-06T13:00:24.178Z
13044,레전드 사건 발생 ㅋㅋㅋㅋㅋㅋ,"[{'name': '동수칸TV', 'url': 'https://www.youtube...",2025-11-06T12:57:02.711Z
13045,의문의 중고차 딜러,"[{'name': '동수칸TV', 'url': 'https://www.youtube...",2025-11-06T12:43:57.489Z
13046,첫 번째 레슨,"[{'name': '동수칸TV', 'url': 'https://www.youtube...",2025-11-06T12:24:23.712Z
13047,저미니스트의 삶,"[{'name': '동수칸TV', 'url': 'https://www.youtube...",2025-11-06T12:01:04.573Z

isinstance(sub_list,list) => sub_list라는 변수에 들어온 녀석이 리스트[] 자료형인지 확인한다.
isinstance(확인하고자 하는 데이터 값, 확인하고자 하는 데이터 타입) => True or False
len(sub_list) > 0 => 아예 없는 경우 방지(안전장치)

sub_list[0] 리스트의 1번째 칸에 있는 딕셔너리{} 선택
get('name') => name이라는 key에 연결된 값(채널명)을 가져온다.

In [44]:
# 채널 이름 추출
def extract_channel(sub_list):
    if isinstance(sub_list, list) and len(sub_list)>0:
        return sub_list[0].get("name")
    return "Unknown"

df["channel"] = df["subtitles"].apply(extract_channel)
df

,title,subtitles,time,channel
0,[𝙋𝙡𝙖𝙮𝙡𝙞𝙨𝙩] 상실의 시대…내가 사랑한 나의 미도리 | 감성 피아노,"[{'name': '노르웨이 숲 Norwegian Wood', 'url': 'htt...",2026-02-04T04:14:52.157Z,노르웨이 숲 Norwegian Wood
1,"과거에는 컴퓨터를 쓰기 위해 복잡한 코딩을 배워야 했지만, 이제는 컴퓨터랑 대화만 ...","[{'name': 'BZCF | 비즈까페', 'url': 'https://www.y...",2026-02-04T04:13:55.202Z,BZCF | 비즈까페
2,요즘 생각 : 너무 빠르고 무섭고 걱정도되고 슬프기도 하고 할수있는 것은 없고 그렇...,"[{'name': 'BZCF | 비즈까페', 'url': 'https://www.y...",2026-02-04T04:13:55.202Z,BZCF | 비즈까페
3,Blue Bird (2022 ver.) - Naruto Shippuuden OP3 ...,"[{'name': 'Animenz Piano Sheets', 'url': 'http...",2026-02-03T23:31:08.546Z,Animenz Piano Sheets
4,TWO-lives,"[{'name': 'Hiroyuki SAWANO - Topic', 'url': 'h...",2026-02-03T23:21:00.923Z,Hiroyuki SAWANO - Topic
...,...,...,...,...
13043,승준이 우유 대소동,"[{'name': '동수칸TV', 'url': 'https://www.youtube...",2025-11-06T13:00:24.178Z,동수칸TV
13044,레전드 사건 발생 ㅋㅋㅋㅋㅋㅋ,"[{'name': '동수칸TV', 'url': 'https://www.youtube...",2025-11-06T12:57:02.711Z,동수칸TV
13045,의문의 중고차 딜러,"[{'name': '동수칸TV', 'url': 'https://www.youtube...",2025-11-06T12:43:57.489Z,동수칸TV
13046,첫 번째 레슨,"[{'name': '동수칸TV', 'url': 'https://www.youtube...",2025-11-06T12:24:23.712Z,동수칸TV
13047,저미니스트의 삶,"[{'name': '동수칸TV', 'url': 'https://www.youtube...",2025-11-06T12:01:04.573Z,동수칸TV

In [45]:
# 기존 데이터 삭제
df.drop(columns=["subtitles"], inplace = True)
df

,title,time,channel
0,[𝙋𝙡𝙖𝙮𝙡𝙞𝙨𝙩] 상실의 시대…내가 사랑한 나의 미도리 | 감성 피아노,2026-02-04T04:14:52.157Z,노르웨이 숲 Norwegian Wood
1,"과거에는 컴퓨터를 쓰기 위해 복잡한 코딩을 배워야 했지만, 이제는 컴퓨터랑 대화만 ...",2026-02-04T04:13:55.202Z,BZCF | 비즈까페
2,요즘 생각 : 너무 빠르고 무섭고 걱정도되고 슬프기도 하고 할수있는 것은 없고 그렇...,2026-02-04T04:13:55.202Z,BZCF | 비즈까페
3,Blue Bird (2022 ver.) - Naruto Shippuuden OP3 ...,2026-02-03T23:31:08.546Z,Animenz Piano Sheets
4,TWO-lives,2026-02-03T23:21:00.923Z,Hiroyuki SAWANO - Topic
...,...,...,...
13043,승준이 우유 대소동,2025-11-06T13:00:24.178Z,동수칸TV
13044,레전드 사건 발생 ㅋㅋㅋㅋㅋㅋ,2025-11-06T12:57:02.711Z,동수칸TV
13045,의문의 중고차 딜러,2025-11-06T12:43:57.489Z,동수칸TV
13046,첫 번째 레슨,2025-11-06T12:24:23.712Z,동수칸TV
13047,저미니스트의 삶,2025-11-06T12:01:04.573Z,동수칸TV

to_datetime => 문자열이었던 시간을 datetime 자료형으로 전환한다. 만약 시간 형식이 제각각이라면
format = 'mixed' / utc값으로 시작한다 확정짓고

한국시간을 위해. dt.tz_convert("Asia/Seoul")로 변경  만약 다른 나라 Asia/Tokyo

In [46]:
#문자열을 날짜/시간 각체로 변환(UTC 기능)
df['time']=pd.to_datetime(df['time'], format ='mixed', utc =True)

df['time_kst']=df['time'].dt.tz_convert("Asia/Seoul")

#년,월, 일, 시, 요일 따로 추출
df['year']= df['time_kst'].dt.year
df['month']=df['time_kst'].dt.month
df['day'] = df['time_kst'].dt.day
df['hour'] = df['time_kst'].dt.hour
df['hour']=df['hour']-9
df["minute"]=df["time_kst"].dt.minute
df['weekday']=df['time_kst'].dt.day_name()

In [51]:
# 먼저 channel 분석
import matplotlib.pyplot as plt
import matplotlib

matplotlib.rcParams["font.family"] = "Malgun Gothic"
matplotlib.rcParams["axes.unicode_minus"]= False

In [56]:
df.sort_values("year",ascending=True)

<bound method IndexOpsMixin.value_counts of 0          노르웨이 숲 Norwegian Wood
1                    BZCF | 비즈까페
2                    BZCF | 비즈까페
3           Animenz Piano Sheets
4        Hiroyuki SAWANO - Topic
                  ...
13043                      동수칸TV
13044                      동수칸TV
13045                      동수칸TV
13046                      동수칸TV
13047                      동수칸TV
Name: channel, Length: 13048, dtype: object>

In [62]:
channel_sort=df.groupby(["channel"]).size()
print(channel_sort)

channel
Allright24_박재훈        138
고기남자                    1
오띵스                     1
  딴짓                     2
 Showboating_Boxing      1
                      ...
힙으뜸                      2
힙플밈                      8
힙한루피 hipster loopy       1
𝕋𝕙𝕖 𝕝𝕒𝕤𝕥 𝕙𝕠𝕦𝕣𝕤 🌊         1
🚨티방위🚨                    1
Length: 3666, dtype: int64