In [40]:
# 시청 기록 파일 가져오기
import pandas as pd
import json

df=pd.read_json("시청 기록.json")

In [41]:
# 데이터 수정 => 최적화.
df.drop(columns= ["header","titleUrl","products","activityControls"], inplace = True)

,title,subtitles,time
0,[𝙋𝙡𝙖𝙮𝙡𝙞𝙨𝙩] 상실의 시대…내가 사랑한 나의 미도리 | 감성 피아노 을(를) ...,"[{'name': '노르웨이 숲 Norwegian Wood', 'url': 'htt...",2026-02-04T04:14:52.157Z
1,"과거에는 컴퓨터를 쓰기 위해 복잡한 코딩을 배워야 했지만, 이제는 컴퓨터랑 대화만 ...","[{'name': 'BZCF | 비즈까페', 'url': 'https://www.y...",2026-02-04T04:13:55.202Z
2,요즘 생각 : 너무 빠르고 무섭고 걱정도되고 슬프기도 하고 할수있는 것은 없고 그렇...,"[{'name': 'BZCF | 비즈까페', 'url': 'https://www.y...",2026-02-04T04:13:55.202Z
3,Blue Bird (2022 ver.) - Naruto Shippuuden OP3 ...,"[{'name': 'Animenz Piano Sheets', 'url': 'http...",2026-02-03T23:31:08.546Z
4,TWO-lives 을(를) 시청했습니다.,"[{'name': 'Hiroyuki SAWANO - Topic', 'url': 'h...",2026-02-03T23:21:00.923Z
...,...,...,...
13043,승준이 우유 대소동 을(를) 시청했습니다.,"[{'name': '동수칸TV', 'url': 'https://www.youtube...",2025-11-06T13:00:24.178Z
13044,레전드 사건 발생 ㅋㅋㅋㅋㅋㅋ 을(를) 시청했습니다.,"[{'name': '동수칸TV', 'url': 'https://www.youtube...",2025-11-06T12:57:02.711Z
13045,의문의 중고차 딜러 을(를) 시청했습니다.,"[{'name': '동수칸TV', 'url': 'https://www.youtube...",2025-11-06T12:43:57.489Z
13046,첫 번째 레슨 을(를) 시청했습니다.,"[{'name': '동수칸TV', 'url': 'https://www.youtube...",2025-11-06T12:24:23.712Z
13047,저미니스트의 삶 을(를) 시청했습니다.,"[{'name': '동수칸TV', 'url': 'https://www.youtube...",2025-11-06T12:01:04.573Z

In [43]:
df

,title,subtitles,time
0,[𝙋𝙡𝙖𝙮𝙡𝙞𝙨𝙩] 상실의 시대…내가 사랑한 나의 미도리 | 감성 피아노 을(를) ...,"[{'name': '노르웨이 숲 Norwegian Wood', 'url': 'htt...",2026-02-04T04:14:52.157Z
1,"과거에는 컴퓨터를 쓰기 위해 복잡한 코딩을 배워야 했지만, 이제는 컴퓨터랑 대화만 ...","[{'name': 'BZCF | 비즈까페', 'url': 'https://www.y...",2026-02-04T04:13:55.202Z
2,요즘 생각 : 너무 빠르고 무섭고 걱정도되고 슬프기도 하고 할수있는 것은 없고 그렇...,"[{'name': 'BZCF | 비즈까페', 'url': 'https://www.y...",2026-02-04T04:13:55.202Z
3,Blue Bird (2022 ver.) - Naruto Shippuuden OP3 ...,"[{'name': 'Animenz Piano Sheets', 'url': 'http...",2026-02-03T23:31:08.546Z
4,TWO-lives 을(를) 시청했습니다.,"[{'name': 'Hiroyuki SAWANO - Topic', 'url': 'h...",2026-02-03T23:21:00.923Z
...,...,...,...
13043,승준이 우유 대소동 을(를) 시청했습니다.,"[{'name': '동수칸TV', 'url': 'https://www.youtube...",2025-11-06T13:00:24.178Z
13044,레전드 사건 발생 ㅋㅋㅋㅋㅋㅋ 을(를) 시청했습니다.,"[{'name': '동수칸TV', 'url': 'https://www.youtube...",2025-11-06T12:57:02.711Z
13045,의문의 중고차 딜러 을(를) 시청했습니다.,"[{'name': '동수칸TV', 'url': 'https://www.youtube...",2025-11-06T12:43:57.489Z
13046,첫 번째 레슨 을(를) 시청했습니다.,"[{'name': '동수칸TV', 'url': 'https://www.youtube...",2025-11-06T12:24:23.712Z
13047,저미니스트의 삶 을(를) 시청했습니다.,"[{'name': '동수칸TV', 'url': 'https://www.youtube...",2025-11-06T12:01:04.573Z