# 6.데이터 선택

In [2]:
import pandas as pd
df = pd.read_excel("score.xlsx", index_col = "지원번호")
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   46  40  35      Python
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [3]:
df["학교"]

지원번호
1번    북산고
2번    북산고
3번    북산고
4번    북산고
5번    북산고
6번    능남고
7번    능남고
8번    능남고
Name: 학교, dtype: object

In [4]:
df[["학교","키"]]

       학교    키
지원번호
1번    북산고  197
2번    북산고  184
3번    북산고  168
4번    북산고  187
5번    북산고  188
6번    능남고  202
7번    능남고  188
8번    능남고  190

In [5]:
df.columns[3]

'국어'

In [7]:
df[df.columns[3]]

지원번호
1번     90
2번     40
3번     80
4번     40
5번     15
6번     80
7번     55
8번    100
Name: 국어, dtype: int64

### 슬라이싱

In [8]:
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   46  40  35      Python
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [9]:
df["영어"][0:4]

지원번호
1번    85
2번    35
3번    75
4번    60
Name: 영어, dtype: int64

In [10]:
df[["키","학교"]][:6]

        키   학교
지원번호
1번    197  북산고
2번    184  북산고
3번    168  북산고
4번    187  북산고
5번    188  북산고
6번    202  능남고

# 7. 데이터 선택(ioc)

이름을 이용하여 원하는 row에서 원하는 col 선택

In [11]:
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   46  40  35      Python
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [12]:
df.loc["1번"]

이름         채치수
학교         북산고
키          197
국어          90
영어          85
수학         100
과학          95
사회          85
SW특기    Python
Name: 1번, dtype: object

In [13]:
df.loc[["3번","6번"],"영어"]

지원번호
3번     75
6번    100
Name: 영어, dtype: int64

In [15]:
df.loc["2번":"6번",:"국어"]

       이름   학교    키  국어
지원번호
2번    정대만  북산고  184  40
3번    송태섭  북산고  168  80
4번    서태웅  북산고  187  40
5번    강백호  북산고  188  15
6번    변덕규  능남고  202  80

# 8.데이터선택(iloc)

위치를 이용하여 원하는 row에서 원하는 col선택

# 9.데이터선택(조건)

조건에 해당하는 데이터 선택

In [19]:
df["키"]>=185

지원번호
1번     True
2번    False
3번    False
4번     True
5번     True
6번     True
7번     True
8번     True
Name: 키, dtype: bool

In [21]:
filt=(df["키"]>180)
df[filt]

       이름   학교    키   국어   영어   수학  과학  사회    SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85  Python
2번    정대만  북산고  184   40   35   50  55  25    Java
4번    서태웅  북산고  187   40   60   70  75  80     NaN
5번    강백호  북산고  188   15   20   10  35  10     NaN
6번    변덕규  능남고  202   80  100   95  85  80       C
7번    황태산  능남고  188   55   65   46  40  35  Python
8번    윤대협  능남고  190  100   85   90  95  95      C#

In [24]:
df.loc[df["키"]>160,"수학"]

지원번호
1번    100
2번     50
3번     70
4번     70
5번     10
6번     95
7번     46
8번     90
Name: 수학, dtype: int64

In [32]:
df.loc[(df["키"]>=185) & (df["학교"]=="북산고")]

       이름   학교    키  국어  영어   수학  과학  사회    SW특기
지원번호
1번    채치수  북산고  197  90  85  100  95  85  Python
4번    서태웅  북산고  187  40  60   70  75  80     NaN
5번    강백호  북산고  188  15  20   10  35  10     NaN

In [35]:
df.loc[(df["키"]<200)|(df["학교"]=="능남고")]

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   46  40  35      Python
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [37]:
filt = df["이름"].str.startswith("송")
df[filt]

       이름   학교    키  국어  영어  수학  과학  사회        SW특기
지원번호
3번    송태섭  북산고  168  80  75  70  80  75  Javascript

In [39]:
langs=["python","java"]
filt= df["SW특기"].str.lower().isin(langs)
df[filt]

       이름   학교    키  국어  영어   수학  과학  사회    SW특기
지원번호
1번    채치수  북산고  197  90  85  100  95  85  Python
2번    정대만  북산고  184  40  35   50  55  25    Java
7번    황태산  능남고  188  55  65   46  40  35  Python