# 예시문제
회원들의 운동데이터(키,몸무게, 골격근량)을 분석하고, 특정 조건에 맞는 우수 회원을 선정하는 프로그램을 작성합니다.

In [6]:
import pandas as pd
import numpy as np


#dict 준비.
data = {
    '이름': ['김근육', '이슬림', '박파워', '최스트롱', '정유연', '한성장', '조성실', '유노력'],
    '성별': ['남', '여', '남', '남', '여', '남', '남', '여'],
    '키': [180, 165, 175, 182, 160, 178, 170, 162],
    '몸무게': [85, 52, 90, 88, 48, 75, 72, 55],
    '골격근량': [40.5, 22.0, np.nan, 42.0, 18.5, 35.0, np.nan, 24.5],
    '체지방률': [18, 25, 28, 15, 22, 20, 17, 24],
    '회원등급': ['Gold', 'Silver', 'Platinum', 'Gold', 'Silver', 'Bronze', 'Gold', 'Silver']   
}

df=pd.DataFrame(data)
df.index = ["M1","M2","M3","M4","M5","M6","M7","M8"]
df.index.name = "회원번호"
df

        이름 성별    키  몸무게  골격근량  체지방률      회원등급
회원번호
M1     김근육  남  180   85  40.5    18      Gold
M2     이슬림  여  165   52  22.0    25    Silver
M3     박파워  남  175   90   NaN    28  Platinum
M4    최스트롱  남  182   88  42.0    15      Gold
M5     정유연  여  160   48  18.5    22    Silver
M6     한성장  남  178   75  35.0    20    Bronze
M7     조성실  남  170   72   NaN    17      Gold
M8     유노력  여  162   55  24.5    24    Silver

In [7]:
filt=df["골격근량"].mean() # df["키"].mean() => 평균값 구하기.
df["골격근량"]=df["골격근량"].fillna(filt) # 왼쪽에 넣어줘야 함.
df

        이름 성별    키  몸무게       골격근량  체지방률      회원등급
회원번호
M1     김근육  남  180   85  40.500000    18      Gold
M2     이슬림  여  165   52  22.000000    25    Silver
M3     박파워  남  175   90  30.416667    28  Platinum
M4    최스트롱  남  182   88  42.000000    15      Gold
M5     정유연  여  160   48  18.500000    22    Silver
M6     한성장  남  178   75  35.000000    20    Bronze
M7     조성실  남  170   72  30.416667    17      Gold
M8     유노력  여  162   55  24.500000    24    Silver

In [8]:
#cm 추가 코드
def add_cm(height):
    return  str(height)+"cm"

df["키"]=df["키"].apply(add_cm)
df

        이름 성별      키  몸무게       골격근량  체지방률      회원등급
회원번호
M1     김근육  남  180cm   85  40.500000    18      Gold
M2     이슬림  여  165cm   52  22.000000    25    Silver
M3     박파워  남  175cm   90  30.416667    28  Platinum
M4    최스트롱  남  182cm   88  42.000000    15      Gold
M5     정유연  여  160cm   48  18.500000    22    Silver
M6     한성장  남  178cm   75  35.000000    20    Bronze
M7     조성실  남  170cm   72  30.416667    17      Gold
M8     유노력  여  162cm   55  24.500000    24    Silver

In [4]:
 # cm 삭제하는 코드
def remove_cm(height):  
    return str(height).replace("cm"," ")

df["키"] = df["키"].apply(remove_cm)
df

        이름 성별     키  몸무게       골격근량  체지방률      회원등급
회원번호
M1     김근육  남  180    85  40.500000    18      Gold
M2     이슬림  여  165    52  22.000000    25    Silver
M3     박파워  남  175    90  30.416667    28  Platinum
M4    최스트롱  남  182    88  42.000000    15      Gold
M5     정유연  여  160    48  18.500000    22    Silver
M6     한성장  남  178    75  35.000000    20    Bronze
M7     조성실  남  170    72  30.416667    17      Gold
M8     유노력  여  162    55  24.500000    24    Silver

In [9]:
# 체지방률 => 체지방(%)
df=df.rename(columns = {"체지방률" : "체지방(%)"})
df

        이름 성별      키  몸무게       골격근량  체지방(%)      회원등급
회원번호
M1     김근육  남  180cm   85  40.500000      18      Gold
M2     이슬림  여  165cm   52  22.000000      25    Silver
M3     박파워  남  175cm   90  30.416667      28  Platinum
M4    최스트롱  남  182cm   88  42.000000      15      Gold
M5     정유연  여  160cm   48  18.500000      22    Silver
M6     한성장  남  178cm   75  35.000000      20    Bronze
M7     조성실  남  170cm   72  30.416667      17      Gold
M8     유노력  여  162cm   55  24.500000      24    Silver

In [10]:
#BMI 계산
def BMI_Cal(row):
    weight = int(row["몸무게"])
    height = int(row["키"].replace("cm",""))  
    BMI = weight/((height/100)**2)
    return BMI

df["BMI"] = df.apply(BMI_Cal, axis =1)
df

        이름 성별      키  몸무게       골격근량  체지방(%)      회원등급        BMI
회원번호
M1     김근육  남  180cm   85  40.500000      18      Gold  26.234568
M2     이슬림  여  165cm   52  22.000000      25    Silver  19.100092
M3     박파워  남  175cm   90  30.416667      28  Platinum  29.387755
M4    최스트롱  남  182cm   88  42.000000      15      Gold  26.566840
M5     정유연  여  160cm   48  18.500000      22    Silver  18.750000
M6     한성장  남  178cm   75  35.000000      20    Bronze  23.671254
M7     조성실  남  170cm   72  30.416667      17      Gold  24.913495
M8     유노력  여  162cm   55  24.500000      24    Silver  20.957171

In [13]:
def get_status(row):
    if row["체지방(%)"]>25:
        return "과체중"
    elif row["체지방(%)"]<18.5: 
        return "저체중"
    return "표준"

df["상태"] = df.apply(get_status, axis=1)
# axis=1 은 가로행으로 한줄씩 읽으면서 이동해 명령. 이걸 써야지 for문처럼 돈다.
# axis = 0 을 쓰면 세로행으로 한줄씩 읽으면서 이동해 명령 => column마다 읽어준다.
df

        이름 성별      키  몸무게       골격근량  체지방(%)      회원등급        BMI   상태
회원번호
M1     김근육  남  180cm   85  40.500000      18      Gold  26.234568  저체중
M2     이슬림  여  165cm   52  22.000000      25    Silver  19.100092   표준
M3     박파워  남  175cm   90  30.416667      28  Platinum  29.387755  과체중
M4    최스트롱  남  182cm   88  42.000000      15      Gold  26.566840  저체중
M5     정유연  여  160cm   48  18.500000      22    Silver  18.750000   표준
M6     한성장  남  178cm   75  35.000000      20    Bronze  23.671254   표준
M7     조성실  남  170cm   72  30.416667      17      Gold  24.913495  저체중
M8     유노력  여  162cm   55  24.500000      24    Silver  20.957171   표준